INSERT INTO work_centers (
  id, code, name, description, cost_per_hour, capacity, efficiency, status, 
  utilization, location, availability, maintenance_schedule, next_maintenance, 
  operator_ids, capabilities, working_hours, oee_score, downtime_hours, 
  productive_hours, metadata, created_at, updated_at
) VALUES 
(
  gen_random_uuid(), 
  'WC-001', 
  'Assembly Line A', 
  'Primary assembly line for wooden furniture', 
  45.00, 
  8, 
  95.00, 
  'active', 
  85.00, 
  'Building A - Floor 1', 
  100.00, 
  'Weekly maintenance on Sundays', 
  '2024-02-04', 
  ARRAY[]::uuid[],
  ARRAY['assembly', 'quality_check', 'packaging'],
  '{"monday": {"start": "08:00", "end": "17:00", "isWorking": true}, "tuesday": {"start": "08:00", "end": "17:00", "isWorking": true}, "wednesday": {"start": "08:00", "end": "17:00", "isWorking": true}, "thursday": {"start": "08:00", "end": "17:00", "isWorking": true}, "friday": {"start": "08:00", "end": "17:00", "isWorking": true}, "saturday": {"start": "08:00", "end": "12:00", "isWorking": false}, "sunday": {"start": "08:00", "end": "12:00", "isWorking": false}}', 
  82.50, 
  2.5, 
  37.5, 
  '{}', 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'WC-002', 
  'Paint Booth 1', 
  'Automated paint booth with drying chamber', 
  60.00, 
  4, 
  88.00, 
  'active', 
  72.00, 
  'Building B - Floor 1', 
  95.00, 
  'Bi-weekly maintenance', 
  '2024-02-10', 
  ARRAY[]::uuid[],
  ARRAY['painting', 'drying', 'quality_check'],
  '{"monday": {"start": "08:00", "end": "17:00", "isWorking": true}, "tuesday": {"start": "08:00", "end": "17:00", "isWorking": true}, "wednesday": {"start": "08:00", "end": "17:00", "isWorking": true}, "thursday": {"start": "08:00", "end": "17:00", "isWorking": true}, "friday": {"start": "08:00", "end": "17:00", "isWorking": true}, "saturday": {"start": "08:00", "end": "12:00", "isWorking": false}, "sunday": {"start": "08:00", "end": "12:00", "isWorking": false}}', 
  75.20, 
  4.0, 
  36.0, 
  '{}', 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'WC-003', 
  'CNC Machine 1', 
  '5-axis CNC machine for precision cutting', 
  120.00, 
  2, 
  92.00, 
  'maintenance', 
  0.00, 
  'Building A - Floor 2', 
  0.00, 
  'Monthly maintenance', 
  '2024-02-01', 
  ARRAY[]::uuid[],
  ARRAY['cutting', 'drilling', 'milling', 'precision_work'],
  '{"monday": {"start": "06:00", "end": "22:00", "isWorking": true}, "tuesday": {"start": "06:00", "end": "22:00", "isWorking": true}, "wednesday": {"start": "06:00", "end": "22:00", "isWorking": true}, "thursday": {"start": "06:00", "end": "22:00", "isWorking": true}, "friday": {"start": "06:00", "end": "22:00", "isWorking": true}, "saturday": {"start": "08:00", "end": "16:00", "isWorking": true}, "sunday": {"start": "08:00", "end": "12:00", "isWorking": false}}', 
  0.00, 
  40.0, 
  0.0, 
  '{"maintenance_reason": "Scheduled preventive maintenance"}', 
  NOW(), 
  NOW()
);
